### ISSUE TITLE
Add the standard image.Image output

### ISSUE THREAD

**Issue by slntopp** [KangSpace/gqrcode#2]
It would have been perfect to be able to generate the standard `image.Image`, like `image.NRGBA` instead of already encoded PNG.

Or, if it is already possible, provide a documentation of how to do it.
Because I can see `core/output` has an `Output` interface with the `GetImage()` method, but couldn't figure how to get access to it.

Thanks!

**Comment by KangSpace** [comment]
`GetImage()` in `Output` interface actually returned is the encoded image format passed in when generating `OutPut`.
Like:
```
fileName := "test.png"
out := output.NewPNGOutput(imageSize)
quietZone := model.AutoQuietZone
qrcode, err = gqrcode.NewQRCode0(data, cons.QrcodeModel2, nil, mode.NewNumericMode(), quietZone)
if err != nil {
    t.Fatal(err)
}
qrcode.Encode(out, fileName)
```

There provide `PNG`, `JPG` and `GIF` formats, which you can find in `image_output.go`.
